export const profileConstants = {
  GET_BY_ID_REQUEST: 'PROFILE_GET_BY_ID_REQUEST',
  GET_BY_ID_SUCCESS: 'PROFILE_GET_BY_ID_SUCCESS',
  GET_BY_ID_FAILURE: 'PROFILE_GET_BY_ID_FAILURE',

  GET_ALL_AVAILABLE_VALUES_REQUEST: 'PROFILE_GET_ALL_AVAILABLE_VALUES_REQUEST',
  GET_ALL_AVAILABLE_VALUES_SUCCESS: 'PROFILE_GET_ALL_AVAILABLE_VALUES_SUCCESS',
  GET_ALL_AVAILABLE_VALUES_FAILURE: 'PROFILE_GET_ALL_AVAILABLE_VALUES_FAILURE',

  UPDATE_FULL_BY_ID_REQUEST: 'PROFILE_UPDATE_FULL_BY_ID_REQUEST',
  UPDATE_FULL_BY_ID_SUCCESS: 'PROFILE_UPDATE_FULL_BY_ID_SUCCESS',
  UPDATE_FULL_BY_ID_FAILURE: 'PROFILE_UPDATE_FULL_BY_ID_FAILURE',

  UPDATE_BY_ID_REQUEST: 'PROFILE_UPDATE_BY_ID_REQUEST',
  UPDATE_BY_ID_SUCCESS: 'PROFILE_UPDATE_BY_ID_SUCCESS',
  UPDATE_BY_ID_FAILURE: 'PROFILE_UPDATE_BY_ID_FAILURE',
};

export const profileValuesConstants = {
  BUDGET: 'budget',
  BUDGET_MIN: 'budget.min',
  BUDGET_MAX: 'budget.max',
  MIN: 'min',
  MAX: 'max',
  INTERESTS: 'interests',
  PLACES: 'places',
  PLACES_LIKED: 'places.likes',
  PLACES_DISLIKED: 'places.dislikes',
  LIKES: 'likes',
  DISLIKES: 'dislikes',
};

export const profileBudgetConstants = {
  MIN_BUDGET: 0,
  MAX_BUDGET: 500,
};
