export const recommendationConstants = {
  GET_RANDOM_REQUEST: 'RECOMMENDATION_GET_RANDOM_REQUEST',
  GET_RANDOM_SUCCESS: 'RECOMMENDATION_GET_RANDOM_SUCCESS',
  GET_RANDOM_FAILURE: 'RECOMMENDATION_GET_RANDOM_FAILURE',

  GET_BY_PROFILE_REQUEST: 'RECOMMENDATION_GET_BY_PROFILE_REQUEST',
  GET_BY_PROFILE_SUCCESS: 'RECOMMENDATION_GET_BY_PROFILE_SUCCESS',
  GET_BY_PROFILE_FAILURE: 'RECOMMENDATION_GET_BY_PROFILE_FAILURE',

  GET_BY_IMAGE_REQUEST: 'RECOMMENDATION_GET_BY_IMAGE_REQUEST',
  GET_BY_IMAGE_SUCCESS: 'RECOMMENDATION_GET_BY_IMAGE_SUCCESS',
  GET_BY_IMAGE_FAILURE: 'RECOMMENDATION_GET_BY_IMAGE_FAILURE',
};

export const recommendationValuesConstants = {
  NAME: 'name',
  DESCRIPTION: 'description',
  REVIEWS: 'reviews',
  TEXT: 'text',
  SCORE: 'score',
  TRAFFIC: 'traffic',
  WEATHER: 'weather',
  BUDGET: 'budget',
  IMAGES: 'images',
};
